version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5014 metrics:app --reload
    
    environment:
      - FLASK_APP=metrics.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5014:5014"
    volumes:
      - ./:/root
    restart: always
